import type {Metadata} from 'next';
import {notFound,permanentRedirect} from 'next/navigation';
import {Header,Footer} from '../../shared';
import {hasProductPhoto,imageCaption,largeProductImage,modelSource,productImage,productPrice} from '@/lib/catalog';
import {publicProducts} from '@/lib/seo-server';
import {absoluteUrl,categoryPath,jsonLd,productIdFromSlug,productPath} from '@/lib/seo';
import {ProductCards} from '../components';
import {ProductVisual} from '../../product-visual';
import '../catalog.css';

export const dynamic='force-dynamic';
type Props={params:Promise<{slug:string}>};
async function productFor({params}:Props){const {slug}=await params;const product=(await publicProducts()).find(p=>p.id===productIdFromSlug(slug));if(!product)notFound();if(productPath(product)!==`/catalog/${encodeURIComponent(slug)}`)permanentRedirect(productPath(product));return product;}
export async function generateMetadata(props:Props):Promise<Metadata>{const p=await productFor(props);const description=`${p.title}. ${p.specification}. ${p.description}`.slice(0,240);return {title:p.title,description,alternates:{canonical:productPath(p)},openGraph:{title:p.title,description,type:'website',url:absoluteUrl(productPath(p)),images:hasProductPhoto(p.image)?[{url:absoluteUrl(productImage(p.image)),alt:p.title}]:[]}};}
export default async function ProductPage(props:Props){
  const p=await productFor(props);const source=modelSource(p);const related=(await publicProducts()).filter(other=>other.category===p.category&&other.id!==p.id).slice(0,4);
  const data={'@context':'https://schema.org','@graph':[{'@type':'Product',name:p.title,description:p.description,...(hasProductPhoto(p.image)?{image:absoluteUrl(productImage(p.image))}:{}),url:absoluteUrl(productPath(p)),sku:p.sku,...(p.brand?{brand:{'@type':'Brand',name:p.brand}}:{}),...(p.model?{model:p.model}:{}),category:p.category,additionalProperty:[{'@type':'PropertyValue',name:'Характеристики',value:p.specification},{'@type':'PropertyValue',name:'Хладагент',value:p.refrigerant}]},{'@type':'BreadcrumbList',itemListElement:[{name:'Главная',item:absoluteUrl('/')},{name:'Каталог',item:absoluteUrl('/catalog')},{name:p.category,item:absoluteUrl(categoryPath(p.category))},{name:p.title,item:absoluteUrl(productPath(p))}].map((item,i)=>({'@type':'ListItem',position:i+1,...item}))}]};
  return <><Header/><main className="wrap page-main public-catalog"><nav className="catalog-breadcrumbs" aria-label="Хлебные крошки"><a href="/">Главная</a><span>/</span><a href="/catalog">Каталог</a><span>/</span><a href={categoryPath(p.category)}>{p.category}</a><span>/</span><span>{p.model||p.title}</span></nav><article className="public-product"><figure className="public-product-image">{hasProductPhoto(p.image)?<a href={largeProductImage(p.image)} target="_blank" rel="noreferrer" aria-label="Открыть фотографию крупно"><ProductVisual product={p} width="600" height="600" fetchPriority="high"/></a>:<ProductVisual product={p}/>}<figcaption>{imageCaption(p.image)}{hasProductPhoto(p.image)&&<>. <a href="/credits" className="source-link">Источник фотографии</a></>}</figcaption></figure><div><p className="eyebrow">{p.category}</p><h1>{p.title}</h1><p className="catalog-lead">{p.description}</p><dl className="product-facts">{[['Бренд',p.brand],['Модель',p.model],['Серия',p.series],['Хладагент',p.refrigerant],['Характеристики',p.specification],['Артикул каталога',p.sku]].filter(([,value])=>value).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="public-product-price">{productPrice(p)}</p><p className="public-product-note">{p.demo?'Цена приведена как ориентир. Остатки тестовые и не подтверждают наличие на складе. Точную стоимость, комплектацию и наличие необходимо уточнить перед заказом.':'Точную комплектацию, наличие и условия поставки уточняйте перед заказом.'}</p>{source&&<a className="source-link" href={source} target="_blank" rel="noreferrer">Документ по модели ↗</a>}<div className="public-product-links"><a className="primary" href={`/?product=${encodeURIComponent(p.id)}`}>Открыть на витрине</a><a className="secondary" href={categoryPath(p.category)}>Все товары раздела</a></div></div></article>{related.length>0&&<section className="public-product-related"><h2>Другие модели в разделе</h2><ProductCards products={related}/></section>}<script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(data)}}/></main><Footer/></>;
}
