import type {Product} from './catalog';
export const catalogProducts:Product[]=[
  {
    "id": "demo-r1",
    "sku": "DEMO-R001",
    "title": "Хладагент TR Gas R134a · 13,6 кг",
    "category": "Хладагенты",
    "description": "Хладагент R134a из каталога TR Gas / Tura. Фасовка 13,6 кг. На фотографии — оригинальная упаковка с обозначением хладагента. Совместимость подбирается по паспорту оборудования.",
    "refrigerant": "R134a",
    "specification": "13,6 кг · баллон",
    "price": 1707000,
    "stock": 8,
    "image": "/products/real-trgas-r134a.webp",
    "active": 1,
    "demo": 1,
    "brand": "TR Gas",
    "model": "R134a",
    "series": "TR Gas"
  },
  {
    "id": "demo-f1",
    "sku": "DEMO-F001",
    "title": "Медные фитинги для монтажа",
    "category": "Комплектующие",
    "description": "Демонстрационный набор медных соединений. Размеры, комплектация и совместимость будут заменены данными склада. Фотография иллюстрирует категорию.",
    "refrigerant": "Универсальный",
    "specification": "Медь · пример комплекта",
    "price": 85000,
    "stock": 35,
    "image": "/products/fittings.jpg",
    "active": 1,
    "demo": 1,
    "brand": "",
    "model": "",
    "series": ""
  },
  {
    "id": "demo-r2",
    "sku": "DEMO-R002",
    "title": "Хладагент TR Gas R410A · 10 кг",
    "category": "Хладагенты",
    "description": "Хладагент R410A из каталога TR Gas / Tura. Фасовка 10 кг. На фотографии — оригинальная упаковка с обозначением хладагента. Совместимость подбирается по паспорту оборудования.",
    "refrigerant": "R410A",
    "specification": "10 кг · баллон",
    "price": 2550000,
    "stock": 0,
    "image": "/products/real-trgas-r410a.webp",
    "active": 1,
    "demo": 1,
    "brand": "TR Gas",
    "model": "R410A",
    "series": "TR Gas"
  },
  {
    "id": "demo-f2",
    "sku": "DEMO-F002",
    "title": "Соединения холодильного контура",
    "category": "Комплектующие",
    "description": "Пример монтажных соединений для холодильного контура. Фактические размеры и характеристики будут указаны владельцем. Фотография иллюстрирует категорию.",
    "refrigerant": "Универсальный",
    "specification": "Медь · пример комплекта",
    "price": 120000,
    "stock": 20,
    "image": "/products/fittings.jpg",
    "active": 1,
    "demo": 1,
    "brand": "",
    "model": "",
    "series": ""
  },
  {
    "id": "premium-r003",
    "sku": "DEMO-R003",
    "title": "Хладагент TR Gas R600a · 420 г",
    "category": "Хладагенты",
    "description": "Хладагент R600a из каталога TR Gas / Tura. Фасовка 420 г. На фотографии — оригинальная упаковка с обозначением хладагента. Совместимость подбирается по паспорту оборудования. R600a — изобутан; не путать с R600. На витрине показан баллончик 420 г.",
    "refrigerant": "R600a",
    "specification": "420 г · баллончик",
    "price": 0,
    "stock": 16,
    "image": "/products/real-trgas-r600a.webp",
    "active": 1,
    "demo": 1,
    "brand": "TR Gas",
    "model": "R600a",
    "series": "TR Gas"
  },
  {
    "id": "premium-r004",
    "sku": "DEMO-R004",
    "title": "Хладагент TR Gas R32 · 9 кг",
    "category": "Хладагенты",
    "description": "Хладагент R32 из каталога TR Gas / Tura. Фасовка 9 кг. На фотографии — оригинальная упаковка с обозначением хладагента. Совместимость подбирается по паспорту оборудования.",
    "refrigerant": "R32",
    "specification": "9 кг · баллон",
    "price": 2010000,
    "stock": 24,
    "image": "/products/real-trgas-r32.webp",
    "active": 1,
    "demo": 1,
    "brand": "TR Gas",
    "model": "R32",
    "series": "TR Gas"
  },
  {
    "id": "premium-r005",
    "sku": "DEMO-R005",
    "title": "Хладагент TR Gas R404A · 10 кг",
    "category": "Хладагенты",
    "description": "Хладагент R404A из каталога TR Gas / Tura. Фасовка 10 кг. На фотографии — оригинальная упаковка с обозначением хладагента. Совместимость подбирается по паспорту оборудования.",
    "refrigerant": "R404A",
    "specification": "10 кг · баллон",
    "price": 1980000,
    "stock": 10,
    "image": "/products/real-trgas-r404a.webp",
    "active": 1,
    "demo": 1,
    "brand": "TR Gas",
    "model": "R404A",
    "series": "TR Gas"
  },
  {
    "id": "premium-r006",
    "sku": "DEMO-R006",
    "title": "Хладагент TR Gas R407C · 10 кг",
    "category": "Хладагенты",
    "description": "Хладагент R407C из каталога TR Gas / Tura. Фасовка 10 кг. На фотографии — оригинальная упаковка с обозначением хладагента. Совместимость подбирается по паспорту оборудования.",
    "refrigerant": "R407C",
    "specification": "10 кг · баллон",
    "price": 2550000,
    "stock": 12,
    "image": "/products/real-trgas-r407c.webp",
    "active": 1,
    "demo": 1,
    "brand": "TR Gas",
    "model": "R407C",
    "series": "TR Gas"
  },
  {
    "id": "premium-r007",
    "sku": "DEMO-R007",
    "title": "Архив: хладагент R507A",
    "category": "Хладагенты",
    "description": "Позиция скрыта: оригинальная продукция TR Gas и соответствующее изображение пока не подтверждены.",
    "refrigerant": "R507A",
    "specification": "Коммерческие холодильные системы",
    "price": 1510000,
    "stock": 6,
    "image": "/products/unverified.png",
    "active": 0,
    "demo": 1,
    "brand": "",
    "model": "R507A",
    "series": ""
  },
  {
    "id": "premium-r008",
    "sku": "DEMO-R008",
    "title": "Хладагент TR Gas R290 · 5 кг",
    "category": "Хладагенты",
    "description": "Хладагент R290 из каталога TR Gas / Tura. Фасовка 5 кг. На фотографии — оригинальная упаковка с обозначением хладагента. Совместимость подбирается по паспорту оборудования.",
    "refrigerant": "R290",
    "specification": "5 кг · баллон",
    "price": 0,
    "stock": 18,
    "image": "/products/real-trgas-r290.webp",
    "active": 1,
    "demo": 1,
    "brand": "TR Gas",
    "model": "R290",
    "series": "TR Gas"
  },
  {
    "id": "premium-r009",
    "sku": "DEMO-R009",
    "title": "Архив: хладагент R22",
    "category": "Хладагенты",
    "description": "Позиция скрыта: оригинальная продукция TR Gas и соответствующее изображение пока не подтверждены.",
    "refrigerant": "R22",
    "specification": "Холодильные системы и кондиционирование",
    "price": 890000,
    "stock": 9,
    "image": "/products/unverified.png",
    "active": 0,
    "demo": 1,
    "brand": "",
    "model": "R22",
    "series": ""
  },
  {
    "id": "premium-r010",
    "sku": "DEMO-R010",
    "title": "Архив: хладагент R1234yf",
    "category": "Хладагенты",
    "description": "Позиция скрыта: оригинальная продукция TR Gas и соответствующее изображение пока не подтверждены.",
    "refrigerant": "R1234yf",
    "specification": "Автомобильное кондиционирование",
    "price": 2350000,
    "stock": 4,
    "image": "/products/unverified.png",
    "active": 0,
    "demo": 1,
    "brand": "",
    "model": "R1234yf",
    "series": ""
  },
  {
    "id": "premium-r011",
    "sku": "DEMO-R011",
    "title": "Архив: хладагент R448A",
    "category": "Хладагенты",
    "description": "Позиция скрыта: оригинальная продукция TR Gas и соответствующее изображение пока не подтверждены.",
    "refrigerant": "R448A",
    "specification": "Коммерческие холодильные системы",
    "price": 1850000,
    "stock": 7,
    "image": "/products/unverified.png",
    "active": 0,
    "demo": 1,
    "brand": "",
    "model": "R448A",
    "series": ""
  },
  {
    "id": "premium-r012",
    "sku": "DEMO-R012",
    "title": "Архив: хладагент R449A",
    "category": "Хладагенты",
    "description": "Позиция скрыта: оригинальная продукция TR Gas и соответствующее изображение пока не подтверждены.",
    "refrigerant": "R449A",
    "specification": "Холодильные камеры и торговое оборудование",
    "price": 1920000,
    "stock": 0,
    "image": "/products/unverified.png",
    "active": 0,
    "demo": 1,
    "brand": "",
    "model": "R449A",
    "series": ""
  },
  {
    "id": "premium-f003",
    "sku": "DEMO-F003",
    "title": "Термостат для холодильника",
    "category": "Комплектующие",
    "description": "Пример запчасти или монтажного материала. Размер, рабочее давление, напряжение и применимость нужно сверить с паспортом реального изделия. Фото иллюстрирует товарную группу. Демонстрационная карточка. Фасовка, комплектация и параметры требуют подтверждения по реальному каталогу склада; цена и остаток тестовые.",
    "refrigerant": "По спецификации",
    "specification": "Механическое управление температурой",
    "price": 185000,
    "stock": 25,
    "image": "/products/thermostat.jpg",
    "active": 1,
    "demo": 1,
    "brand": "",
    "model": "",
    "series": ""
  },
  {
    "id": "premium-f004",
    "sku": "DEMO-F004",
    "title": "Термостат для морозильника",
    "category": "Комплектующие",
    "description": "Пример запчасти или монтажного материала. Размер, рабочее давление, напряжение и применимость нужно сверить с паспортом реального изделия. Фото иллюстрирует товарную группу. Демонстрационная карточка. Фасовка, комплектация и параметры требуют подтверждения по реальному каталогу склада; цена и остаток тестовые.",
    "refrigerant": "По спецификации",
    "specification": "Механическое управление температурой",
    "price": 265000,
    "stock": 20,
    "image": "/products/thermostat.jpg",
    "active": 1,
    "demo": 1,
    "brand": "",
    "model": "",
    "series": ""
  },
  {
    "id": "premium-f005",
    "sku": "DEMO-F005",
    "title": "Термостат для холодильной витрины",
    "category": "Комплектующие",
    "description": "Пример запчасти или монтажного материала. Размер, рабочее давление, напряжение и применимость нужно сверить с паспортом реального изделия. Фото иллюстрирует товарную группу. Демонстрационная карточка. Фасовка, комплектация и параметры требуют подтверждения по реальному каталогу склада; цена и остаток тестовые.",
    "refrigerant": "По спецификации",
    "specification": "Контроль температуры · пример позиции",
    "price": 345000,
    "stock": 18,
    "image": "/products/thermostat.jpg",
    "active": 1,
    "demo": 1,
    "brand": "",
    "model": "",
    "series": ""
  },
  {
    "id": "premium-f006",
    "sku": "DEMO-F006",
    "title": "Термостат с капиллярным датчиком",
    "category": "Комплектующие",
    "description": "Пример запчасти или монтажного материала. Размер, рабочее давление, напряжение и применимость нужно сверить с паспортом реального изделия. Фото иллюстрирует товарную группу. Демонстрационная карточка. Фасовка, комплектация и параметры требуют подтверждения по реальному каталогу склада; цена и остаток тестовые.",
    "refrigerant": "По спецификации",
    "specification": "Управление холодильным контуром",
    "price": 45000,
    "stock": 30,
    "image": "/products/thermostat.jpg",
    "active": 1,
    "demo": 1,
    "brand": "",
    "model": "",
    "series": ""
  },
  {
    "id": "premium-f007",
    "sku": "DEMO-F007",
    "title": "Пусковой конденсатор для компрессора",
    "category": "Комплектующие",
    "description": "Пример запчасти или монтажного материала. Размер, рабочее давление, напряжение и применимость нужно сверить с паспортом реального изделия. Фото иллюстрирует товарную группу. Демонстрационная карточка. Фасовка, комплектация и параметры требуют подтверждения по реальному каталогу склада; цена и остаток тестовые.",
    "refrigerant": "По спецификации",
    "specification": "Электрические комплектующие",
    "price": 95000,
    "stock": 15,
    "image": "/products/capacitor.jpg",
    "active": 1,
    "demo": 1,
    "brand": "",
    "model": "",
    "series": ""
  },
  {
    "id": "premium-f008",
    "sku": "DEMO-F008",
    "title": "Конденсатор для электродвигателя",
    "category": "Комплектующие",
    "description": "Пример запчасти или монтажного материала. Размер, рабочее давление, напряжение и применимость нужно сверить с паспортом реального изделия. Фото иллюстрирует товарную группу. Демонстрационная карточка. Фасовка, комплектация и параметры требуют подтверждения по реальному каталогу склада; цена и остаток тестовые.",
    "refrigerant": "По спецификации",
    "specification": "Электрические комплектующие",
    "price": 115000,
    "stock": 12,
    "image": "/products/capacitor.jpg",
    "active": 1,
    "demo": 1,
    "brand": "",
    "model": "",
    "series": ""
  },
  {
    "id": "premium-f009",
    "sku": "DEMO-F009",
    "title": "Пусковой конденсатор",
    "category": "Комплектующие",
    "description": "Пример запчасти или монтажного материала. Размер, рабочее давление, напряжение и применимость нужно сверить с паспортом реального изделия. Фото иллюстрирует товарную группу. Демонстрационная карточка. Фасовка, комплектация и параметры требуют подтверждения по реальному каталогу склада; цена и остаток тестовые.",
    "refrigerant": "По спецификации",
    "specification": "Электрические комплектующие",
    "price": 65000,
    "stock": 22,
    "image": "/products/capacitor.jpg",
    "active": 1,
    "demo": 1,
    "brand": "",
    "model": "",
    "series": ""
  },
  {
    "id": "premium-f010",
    "sku": "DEMO-F010",
    "title": "Рабочий конденсатор",
    "category": "Комплектующие",
    "description": "Пример запчасти или монтажного материала. Размер, рабочее давление, напряжение и применимость нужно сверить с паспортом реального изделия. Фото иллюстрирует товарную группу. Демонстрационная карточка. Фасовка, комплектация и параметры требуют подтверждения по реальному каталогу склада; цена и остаток тестовые.",
    "refrigerant": "По спецификации",
    "specification": "Электрические комплектующие",
    "price": 75000,
    "stock": 16,
    "image": "/products/capacitor.jpg",
    "active": 1,
    "demo": 1,
    "brand": "",
    "model": "",
    "series": ""
  },
  {
    "id": "premium-f011",
    "sku": "DEMO-F011",
    "title": "Муфта медная под пайку",
    "category": "Комплектующие",
    "description": "Пример запчасти или монтажного материала. Размер, рабочее давление, напряжение и применимость нужно сверить с паспортом реального изделия. Фото иллюстрирует товарную группу. Демонстрационная карточка. Фасовка, комплектация и параметры требуют подтверждения по реальному каталогу склада; цена и остаток тестовые.",
    "refrigerant": "По спецификации",
    "specification": "Монтажные соединения",
    "price": 18000,
    "stock": 40,
    "image": "/products/fittings.jpg",
    "active": 1,
    "demo": 1,
    "brand": "",
    "model": "",
    "series": ""
  },
  {
    "id": "premium-f012",
    "sku": "DEMO-F012",
    "title": "Уголок медный 90°",
    "category": "Комплектующие",
    "description": "Пример запчасти или монтажного материала. Размер, рабочее давление, напряжение и применимость нужно сверить с паспортом реального изделия. Фото иллюстрирует товарную группу. Демонстрационная карточка. Фасовка, комплектация и параметры требуют подтверждения по реальному каталогу склада; цена и остаток тестовые.",
    "refrigerant": "По спецификации",
    "specification": "Монтажные соединения",
    "price": 22000,
    "stock": 35,
    "image": "/products/fittings.jpg",
    "active": 1,
    "demo": 1,
    "brand": "",
    "model": "",
    "series": ""
  },
  {
    "id": "premium-f013",
    "sku": "DEMO-F013",
    "title": "Тройник медный",
    "category": "Комплектующие",
    "description": "Пример запчасти или монтажного материала. Размер, рабочее давление, напряжение и применимость нужно сверить с паспортом реального изделия. Фото иллюстрирует товарную группу. Демонстрационная карточка. Фасовка, комплектация и параметры требуют подтверждения по реальному каталогу склада; цена и остаток тестовые.",
    "refrigerant": "По спецификации",
    "specification": "Монтажные соединения",
    "price": 35000,
    "stock": 28,
    "image": "/products/fittings.jpg",
    "active": 1,
    "demo": 1,
    "brand": "",
    "model": "",
    "series": ""
  },
  {
    "id": "premium-f014",
    "sku": "DEMO-F014",
    "title": "Переходник медный",
    "category": "Комплектующие",
    "description": "Пример запчасти или монтажного материала. Размер, рабочее давление, напряжение и применимость нужно сверить с паспортом реального изделия. Фото иллюстрирует товарную группу. Демонстрационная карточка. Фасовка, комплектация и параметры требуют подтверждения по реальному каталогу склада; цена и остаток тестовые.",
    "refrigerant": "По спецификации",
    "specification": "Монтажные соединения",
    "price": 28000,
    "stock": 45,
    "image": "/products/fittings.jpg",
    "active": 1,
    "demo": 1,
    "brand": "",
    "model": "",
    "series": ""
  },
  {
    "id": "premium-t001",
    "sku": "DEMO-T001",
    "title": "Манометрический коллектор VALUE VMG-2-R410A-B",
    "category": "Инструменты",
    "description": "Двухвентильный аналоговый коллектор для контроля давления и заправки систем с R22, R134a, R410A и R407C.",
    "refrigerant": "R22 / R134a / R410A / R407C",
    "specification": "2 вентиля · манометры 68 мм · 3 шланга 120 см · кейс",
    "price": 1550000,
    "stock": 8,
    "image": "/products/real-value-vmg-2-r410a-b.webp",
    "active": 1,
    "demo": 1,
    "brand": "VALUE",
    "model": "VMG-2-R410A-B",
    "series": "VMG"
  },
  {
    "id": "premium-t002",
    "sku": "DEMO-T002",
    "title": "Мини-труборез VALUE VTC-28",
    "category": "Инструменты",
    "description": "Компактный роликовый труборез для медных и алюминиевых труб диаметром 4–28 мм. Удобен при работе в ограниченном пространстве.",
    "refrigerant": "По паспорту оборудования",
    "specification": "4–28 мм · 1/8″–1 1/8″ · ручной",
    "price": 85000,
    "stock": 6,
    "image": "/products/real-value-vtc-28.webp",
    "active": 1,
    "demo": 1,
    "brand": "VALUE",
    "model": "VTC-28",
    "series": "VTC"
  },
  {
    "id": "premium-t003",
    "sku": "DEMO-T003",
    "title": "Цифровой коллектор VALUE VDG-S1",
    "category": "Инструменты",
    "description": "Одновентильный цифровой коллектор низкого давления. ЖК-дисплей с подсветкой, смотровое стекло и поддержка 9 хладагентов.",
    "refrigerant": "По паспорту оборудования",
    "specification": "1 вентиль · 2 × 1/4″ SAE · питание 9 В · шланги и кейс",
    "price": 2460000,
    "stock": 10,
    "image": "/products/real-value-vdg-s1.webp",
    "active": 1,
    "demo": 1,
    "brand": "VALUE",
    "model": "VDG-S1",
    "series": "VDG"
  },
  {
    "id": "premium-t004",
    "sku": "DEMO-T004",
    "title": "Вакуумный насос VALUE VE115N",
    "category": "Инструменты",
    "description": "Одноступенчатый масляный вакуумный насос для вакуумирования холодильных контуров перед заправкой хладагентом.",
    "refrigerant": "По паспорту оборудования",
    "specification": "51 л/мин при 50 Гц · 1 ступень · 150 микрон · 220 В",
    "price": 990000,
    "stock": 5,
    "image": "/products/real-value-ve115n.webp",
    "active": 1,
    "demo": 1,
    "brand": "VALUE",
    "model": "VE115N",
    "series": "VE N"
  },
  {
    "id": "premium-t005",
    "sku": "DEMO-T005",
    "title": "Вакуумный насос VALUE VE125N",
    "category": "Инструменты",
    "description": "Одноступенчатый масляный насос с производительностью 70 л/мин для монтажа и обслуживания холодильных систем.",
    "refrigerant": "По паспорту оборудования",
    "specification": "70 л/мин при 50 Гц · 1 ступень · 150 микрон · 220 В",
    "price": 2290000,
    "stock": 4,
    "image": "/products/real-value-ve125n.webp",
    "active": 1,
    "demo": 1,
    "brand": "VALUE",
    "model": "VE125N",
    "series": "VE N"
  },
  {
    "id": "premium-t006",
    "sku": "DEMO-T006",
    "title": "Вакуумный насос VALUE VE215N",
    "category": "Инструменты",
    "description": "Двухступенчатый масляный насос для глубокого вакуумирования холодильных контуров. Компактная модель серии VE N.",
    "refrigerant": "По паспорту оборудования",
    "specification": "42 л/мин при 50 Гц · 2 ступени · 15 микрон · 220 В",
    "price": 3450000,
    "stock": 3,
    "image": "/products/real-value-ve215n.webp",
    "active": 1,
    "demo": 1,
    "brand": "VALUE",
    "model": "VE215N",
    "series": "VE N"
  },
  {
    "id": "premium-t007",
    "sku": "DEMO-T007",
    "title": "Труборез VALUE VTC-32",
    "category": "Инструменты",
    "description": "Роликовый труборез для медных и алюминиевых труб. Модель с регулировочной рукояткой для диаметров 4–32 мм.",
    "refrigerant": "По паспорту оборудования",
    "specification": "4–32 мм · 1/8″–1 1/4″ · ручной",
    "price": 190000,
    "stock": 7,
    "image": "/products/real-value-vtc-32.webp",
    "active": 1,
    "demo": 1,
    "brand": "VALUE",
    "model": "VTC-32",
    "series": "VTC"
  },
  {
    "id": "premium-t008",
    "sku": "DEMO-T008",
    "title": "Вакуумный насос VALUE VE245N",
    "category": "Инструменты",
    "description": "Двухступенчатый масляный насос повышенной производительности для вакуумирования систем кондиционирования и холодильного оборудования.",
    "refrigerant": "По паспорту оборудования",
    "specification": "128 л/мин при 50 Гц · 2 ступени · 15 микрон · 220 В",
    "price": 2500000,
    "stock": 0,
    "image": "/products/real-value-ve245n.webp",
    "active": 1,
    "demo": 1,
    "brand": "VALUE",
    "model": "VE245N",
    "series": "VE N"
  },
  {
    "id": "model-secop-tles4-8kk-3",
    "sku": "DEMO-M001",
    "title": "Компрессор Secop TLES4.8KK.3",
    "brand": "Danfoss / Secop",
    "model": "TLES4.8KK.3",
    "series": "TL/TLES",
    "category": "Холодильные компрессоры",
    "description": "Низкотемпературный герметичный компрессор серии TLES для холодильной техники. Архивная модель. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. Secop — бывшее подразделение Danfoss Household Compressors. TLES4.8KK.3: фотография модели, заводской шильдик сохранён.",
    "refrigerant": "R600a",
    "specification": "Для холодильной техники · Архивная модель",
    "price": 980000,
    "stock": 4,
    "image": "/products/real-compressor-tles4-8kk-3.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-secop-tl5g",
    "sku": "DEMO-M002",
    "title": "Компрессор Secop TL5G",
    "brand": "Danfoss / Secop",
    "model": "TL5G",
    "series": "TL",
    "category": "Холодильные компрессоры",
    "description": "Универсальная модель серии TL для холодильной техники. Архивная серия. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. Secop — бывшее подразделение Danfoss Household Compressors. TL5G: фотография модели, заводской шильдик сохранён.",
    "refrigerant": "R134a / R513A",
    "specification": "Для холодильной техники · Архивная модель",
    "price": 1065000,
    "stock": 5,
    "image": "/products/real-compressor-tl5g.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-secop-nl6-1mf",
    "sku": "DEMO-M003",
    "title": "Компрессор Secop NL6.1MF",
    "brand": "Danfoss / Secop",
    "model": "NL6.1MF",
    "series": "NL",
    "category": "Холодильные компрессоры",
    "description": "Герметичный компрессор серии NL для холодильных применений LBP и MBP. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. Secop — бывшее подразделение Danfoss Household Compressors. NL6.1MF: фотография модели, заводской шильдик сохранён.",
    "refrigerant": "R134a / R513A",
    "specification": "Для холодильной техники",
    "price": 1150000,
    "stock": 6,
    "image": "/products/real-compressor-nl6-1mf.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-secop-nl11f",
    "sku": "DEMO-M004",
    "title": "Компрессор Secop NL11F",
    "brand": "Danfoss / Secop",
    "model": "NL11F",
    "series": "NL",
    "category": "Холодильные компрессоры",
    "description": "Низкотемпературная модель серии NL для холодильной техники. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. Secop — бывшее подразделение Danfoss Household Compressors. NL11F: фотография модели, заводской шильдик сохранён.",
    "refrigerant": "R134a",
    "specification": "Для холодильной техники",
    "price": 1235000,
    "stock": 7,
    "image": "/products/real-compressor-nl11f.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-secop-fr8-5g",
    "sku": "DEMO-M005",
    "title": "Компрессор Secop FR8.5G",
    "brand": "Danfoss / Secop",
    "model": "FR8.5G",
    "series": "FR",
    "category": "Холодильные компрессоры",
    "description": "Универсальный холодильный компрессор серии FR. Архивная модель. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. Secop — бывшее подразделение Danfoss Household Compressors. FR8.5G: фотография модели, заводской шильдик сохранён.",
    "refrigerant": "R134a",
    "specification": "Для холодильной техники · Архивная модель",
    "price": 1320000,
    "stock": 8,
    "image": "/products/real-compressor-fr8-5g.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-secop-fr10g",
    "sku": "DEMO-M006",
    "title": "Компрессор Secop FR10G",
    "brand": "Danfoss / Secop",
    "model": "FR10G",
    "series": "FR",
    "category": "Холодильные компрессоры",
    "description": "Герметичный холодильный компрессор серии FR. Архивная модель. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. Secop — бывшее подразделение Danfoss Household Compressors. Secop FR10G. На фото исполнение 103G6880; код в паспорте карточки — 103G6890.",
    "refrigerant": "R134a",
    "specification": "Для холодильной техники · Архивная модель",
    "price": 1405000,
    "stock": 9,
    "image": "/products/real-compressor-fr10g.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "premium-c007",
    "sku": "DEMO-C007",
    "title": "Компрессор Secop SC12CL",
    "brand": "Danfoss / Secop",
    "model": "SC12CL",
    "series": "SC",
    "category": "Холодильные компрессоры",
    "description": "Низкотемпературный компрессор серии SC для холодильного оборудования. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. Secop — бывшее подразделение Danfoss Household Compressors. SC12CL: фотография модели, заводской шильдик сохранён.",
    "refrigerant": "R404A / R452A",
    "specification": "Для холодильной техники",
    "price": 3800000,
    "stock": 3,
    "image": "/products/real-compressor-sc12cl.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "demo-c1",
    "sku": "DEMO-C001",
    "title": "Компрессор Danfoss / Secop SC18CL",
    "brand": "Danfoss / Secop",
    "model": "SC18CL",
    "series": "SC",
    "category": "Холодильные компрессоры",
    "description": "Низкотемпературная модель серии SC для холодильного оборудования. На фото Danfoss / Secop SC18CL; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. Secop — бывшее подразделение Danfoss Household Compressors.",
    "refrigerant": "R404A / R452A",
    "specification": "Для холодильной техники",
    "price": 1250000,
    "stock": 12,
    "image": "/products/compressor.jpg",
    "active": 1,
    "demo": 1
  },
  {
    "id": "premium-c003",
    "sku": "DEMO-C003",
    "title": "Компрессор Embraco EMX55CLC",
    "brand": "Embraco",
    "model": "EMX55CLC",
    "series": "EM",
    "category": "Холодильные компрессоры",
    "description": "Модель семейства EM для низкотемпературной холодильной техники. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные.",
    "refrigerant": "R600a",
    "specification": "Для холодильной техники",
    "price": 1150000,
    "stock": 6,
    "image": "/products/embraco-em-family.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "premium-c004",
    "sku": "DEMO-C004",
    "title": "Компрессор Embraco EMT45HDR",
    "brand": "Embraco",
    "model": "EMT45HDR",
    "series": "EM",
    "category": "Холодильные компрессоры",
    "description": "Холодильный компрессор семейства EM для применений HBP. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные.",
    "refrigerant": "R134a",
    "specification": "Для холодильной техники",
    "price": 1680000,
    "stock": 8,
    "image": "/products/embraco-em-family.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "premium-c006",
    "sku": "DEMO-C006",
    "title": "Компрессор Embraco EMT2121U",
    "brand": "Embraco",
    "model": "EMT2121U",
    "series": "EM",
    "category": "Холодильные компрессоры",
    "description": "Низкотемпературный холодильный компрессор семейства EM. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные.",
    "refrigerant": "R290",
    "specification": "Для холодильной техники",
    "price": 1950000,
    "stock": 7,
    "image": "/products/embraco-em-family.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-embraco-emc3134u",
    "sku": "DEMO-M012",
    "title": "Компрессор Embraco EMC3134U",
    "brand": "Embraco",
    "model": "EMC3134U",
    "series": "EM",
    "category": "Холодильные компрессоры",
    "description": "Модель семейства EM для холодильных применений LBP и MBP. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные.",
    "refrigerant": "R290",
    "specification": "Для холодильной техники",
    "price": 1915000,
    "stock": 6,
    "image": "/products/embraco-em-family.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-embraco-nek6210gk",
    "sku": "DEMO-M013",
    "title": "Компрессор Embraco NEK6210GK",
    "brand": "Embraco",
    "model": "NEK6210GK",
    "series": "NE",
    "category": "Холодильные компрессоры",
    "description": "Среднетемпературный компрессор семейства NE для коммерческого холода. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные.",
    "refrigerant": "R404A / R507A",
    "specification": "Для холодильной техники",
    "price": 2000000,
    "stock": 7,
    "image": "/products/embraco-ne-family.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-embraco-neu6215gk",
    "sku": "DEMO-M014",
    "title": "Компрессор Embraco NEU6215GK",
    "brand": "Embraco",
    "model": "NEU6215GK",
    "series": "NE",
    "category": "Холодильные компрессоры",
    "description": "Компрессор семейства NE для среднетемпературного холодильного оборудования. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные.",
    "refrigerant": "R404A / R507A",
    "specification": "Для холодильной техники",
    "price": 2085000,
    "stock": 8,
    "image": "/products/embraco-ne-family.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-embraco-nt6222gk",
    "sku": "DEMO-M015",
    "title": "Компрессор Embraco NT6222GK",
    "brand": "Embraco",
    "model": "NT6222GK",
    "series": "NT",
    "category": "Холодильные компрессоры",
    "description": "Модель семейства NT для среднетемпературного коммерческого холода. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные.",
    "refrigerant": "R404A / R507A",
    "specification": "Для холодильной техники",
    "price": 2170000,
    "stock": 9,
    "image": "/products/embraco-nt-family.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "premium-c008",
    "sku": "DEMO-C008",
    "title": "Компрессор Embraco NJ9238GK",
    "brand": "Embraco",
    "model": "NJ9238GK",
    "series": "NJ",
    "category": "Холодильные компрессоры",
    "description": "Компрессор семейства NJ для коммерческого холодильного оборудования. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные.",
    "refrigerant": "R404A / R507A",
    "specification": "Для холодильной техники",
    "price": 4250000,
    "stock": 0,
    "image": "/products/embraco-nj-family.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "demo-c2",
    "sku": "DEMO-C002",
    "title": "Компрессор Toshiba DA130A1F-25F",
    "brand": "Toshiba",
    "model": "DA130A1F-25F",
    "series": "DA",
    "category": "Кондиционерные компрессоры",
    "description": "Двухроторный компрессор с инверторным управлением для кондиционеров Toshiba на R410A. Указан в документации RAS-M18UAV-E. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. DA130A1F-25F: фотография модели, заводской шильдик сохранён.",
    "refrigerant": "R410A",
    "specification": "Для кондиционеров",
    "price": 2100000,
    "stock": 4,
    "image": "/products/real-compressor-da130a1f-25f.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-toshiba-da111a1f-20f1",
    "sku": "DEMO-M018",
    "title": "Компрессор Toshiba DA111A1F-20F1",
    "brand": "Toshiba",
    "model": "DA111A1F-20F1",
    "series": "DA",
    "category": "Кондиционерные компрессоры",
    "description": "Компрессор для инверторных кондиционеров Toshiba на R410A. Указан в документации наружного блока RAS-M14GAV-E. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. DA111A1F-20F1: фотография модели, заводской шильдик сохранён.",
    "refrigerant": "R410A",
    "specification": "Для кондиционеров",
    "price": 2425000,
    "stock": 12,
    "image": "/products/real-compressor-da111a1f-20f1.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-toshiba-da89x1c-23fz2",
    "sku": "DEMO-M019",
    "title": "Компрессор Toshiba DA89X1C-23FZ2",
    "brand": "Toshiba",
    "model": "DA89X1C-23FZ2",
    "series": "DA",
    "category": "Кондиционерные компрессоры",
    "description": "Компрессор инверторных кондиционеров Toshiba RAS-10SAV2-E и RAS-13SAV2-E на R410A. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. DA89X1C-23FZ2: фотография модели, заводской шильдик сохранён.",
    "refrigerant": "R410A",
    "specification": "Для кондиционеров",
    "price": 2510000,
    "stock": 4,
    "image": "/products/real-compressor-da89x1c-23fz2.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-toshiba-da130a1f-27f",
    "sku": "DEMO-M020",
    "title": "Компрессор Toshiba DA130A1F-27F",
    "brand": "Toshiba",
    "model": "DA130A1F-27F",
    "series": "DA",
    "category": "Кондиционерные компрессоры",
    "description": "Компрессор для кондиционера Toshiba RAS-18SAV2-E на R410A; точный код подтверждён сервисным каталогом. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. Toshiba серии DA130. На фото DA130A1F-21F; модификация DA130A1F-27F может отличаться.",
    "refrigerant": "R410A",
    "specification": "Для кондиционеров",
    "price": 2595000,
    "stock": 5,
    "image": "/products/real-compressor-da130a1f-27f.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-gmcc-ksk53d15uez3",
    "sku": "DEMO-M021",
    "title": "Компрессор GMCC KSK53D15UEZ3",
    "brand": "GMCC",
    "model": "KSK53D15UEZ3",
    "series": "SK",
    "category": "Кондиционерные компрессоры",
    "description": "Однороторный инверторный компрессор для систем кондиционирования. Модель из каталога GMCC 2024, раздел R32/R410A. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. GMCC серии SK. На фото KSK103D33UEZ3; исполнение KSK53D15UEZ3 может отличаться.",
    "refrigerant": "R32 / R410A",
    "specification": "Для кондиционеров",
    "price": 2680000,
    "stock": 6,
    "image": "/products/real-compressor-ksk53d15uez3.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-gmcc-ksn98d27uer31",
    "sku": "DEMO-M022",
    "title": "Компрессор GMCC KSN98D27UER31",
    "brand": "GMCC",
    "model": "KSN98D27UER31",
    "series": "SN",
    "category": "Кондиционерные компрессоры",
    "description": "Однороторный инверторный компрессор для систем кондиционирования. Модель из каталога GMCC 2024, раздел R32/R410A. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. GMCC серии SN. На фото KSN140D21UFZ; исполнение KSN98D27UER31 может отличаться.",
    "refrigerant": "R32 / R410A",
    "specification": "Для кондиционеров",
    "price": 2765000,
    "stock": 7,
    "image": "/products/real-compressor-ksn98d27uer31.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-gmcc-ktk115d33ufz3",
    "sku": "DEMO-M023",
    "title": "Компрессор GMCC KTK115D33UFZ3",
    "brand": "GMCC",
    "model": "KTK115D33UFZ3",
    "series": "TK",
    "category": "Кондиционерные компрессоры",
    "description": "Двухроторный инверторный компрессор для систем кондиционирования. Модель из каталога GMCC 2024, раздел R32/R410A. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. GMCC серии TK. На фото KTK130D43UFE3; исполнение KTK115D33UFZ3 может отличаться.",
    "refrigerant": "R32 / R410A",
    "specification": "Для кондиционеров",
    "price": 2850000,
    "stock": 8,
    "image": "/products/real-compressor-ktk115d33ufz3.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-gmcc-ktn150d53ufz3",
    "sku": "DEMO-M024",
    "title": "Компрессор GMCC KTN150D53UFZ3",
    "brand": "GMCC",
    "model": "KTN150D53UFZ3",
    "series": "TN",
    "category": "Кондиционерные компрессоры",
    "description": "Двухроторный инверторный компрессор для систем кондиционирования. Модель из каталога GMCC 2024, раздел R32/R410A. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. GMCC серии TN. На фото KTN150D30UFZA; исполнение KTN150D53UFZ3 может отличаться.",
    "refrigerant": "R32 / R410A",
    "specification": "Для кондиционеров",
    "price": 2935000,
    "stock": 9,
    "image": "/products/real-compressor-ktn150d53ufz3.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-gmcc-ktm180d43umt",
    "sku": "DEMO-M025",
    "title": "Компрессор GMCC KTM180D43UMT",
    "brand": "GMCC",
    "model": "KTM180D43UMT",
    "series": "TM",
    "category": "Кондиционерные компрессоры",
    "description": "Двухроторный инверторный компрессор для систем кондиционирования. Модель из каталога GMCC 2024, раздел R32/R410A. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. GMCC серии TM. На фото KTM240D43UKT; исполнение KTM180D43UMT может отличаться.",
    "refrigerant": "R32 / R410A",
    "specification": "Для кондиционеров",
    "price": 3020000,
    "stock": 10,
    "image": "/products/real-compressor-ktm180d43umt.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-gmcc-ktf310d43umt",
    "sku": "DEMO-M026",
    "title": "Компрессор GMCC KTF310D43UMT",
    "brand": "GMCC",
    "model": "KTF310D43UMT",
    "series": "TF",
    "category": "Кондиционерные компрессоры",
    "description": "Двухроторный инверторный компрессор для систем кондиционирования. Модель из каталога GMCC 2024, раздел R32/R410A. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. GMCC KTF310D43UMT: фотография модели, заводской шильдик сохранён.",
    "refrigerant": "R32 / R410A",
    "specification": "Для кондиционеров",
    "price": 3105000,
    "stock": 11,
    "image": "/products/real-compressor-ktf310d43umt.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-highly-asd102skq-6b",
    "sku": "DEMO-M027",
    "title": "Компрессор Highly ASD102SKQ-6B",
    "brand": "Highly",
    "model": "ASD102SKQ-6B",
    "series": "D",
    "category": "Кондиционерные компрессоры",
    "description": "Инверторный компрессор для систем кондиционирования на R410A. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные.",
    "refrigerant": "R410A",
    "specification": "Для кондиционеров",
    "price": 3190000,
    "stock": 12,
    "image": "/products/highly-asd-family.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-highly-asg133skq",
    "sku": "DEMO-M028",
    "title": "Компрессор Highly ASG133SKQ",
    "brand": "Highly",
    "model": "ASG133SKQ",
    "series": "G",
    "category": "Кондиционерные компрессоры",
    "description": "Инверторный компрессор для систем кондиционирования на R410A. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные.",
    "refrigerant": "R410A",
    "specification": "Для кондиционеров",
    "price": 3275000,
    "stock": 4,
    "image": "/products/highly-asd-family.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-highly-atl232udp-1",
    "sku": "DEMO-M029",
    "title": "Компрессор Highly ATL232UDP-1",
    "brand": "Highly",
    "model": "ATL232UDP-1",
    "series": "L",
    "category": "Кондиционерные компрессоры",
    "description": "Инверторный компрессор для систем кондиционирования на R410A. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные.",
    "refrigerant": "R410A",
    "specification": "Для кондиционеров",
    "price": 3360000,
    "stock": 5,
    "image": "/products/highly-asd-family.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-highly-ath307sd",
    "sku": "DEMO-M030",
    "title": "Компрессор Highly ATH307SD",
    "brand": "Highly",
    "model": "ATH307SD",
    "series": "TH",
    "category": "Кондиционерные компрессоры",
    "description": "Инверторный компрессор для систем кондиционирования на R410A. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные.",
    "refrigerant": "R410A",
    "specification": "Для кондиционеров",
    "price": 3445000,
    "stock": 6,
    "image": "/products/highly-asd-family.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-highly-ash184tv-1",
    "sku": "DEMO-M031",
    "title": "Компрессор Highly ASH184TV-1",
    "brand": "Highly",
    "model": "ASH184TV-1",
    "series": "H",
    "category": "Кондиционерные компрессоры",
    "description": "Роторный компрессор постоянной скорости для кондиционеров на R410A. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные.",
    "refrigerant": "R410A",
    "specification": "Для кондиционеров",
    "price": 3530000,
    "stock": 7,
    "image": "/products/highly-asd-family.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-highly-gsd088skq-6",
    "sku": "DEMO-M032",
    "title": "Компрессор Highly GSD088SKQ-6",
    "brand": "Highly",
    "model": "GSD088SKQ-6",
    "series": "D",
    "category": "Кондиционерные компрессоры",
    "description": "Инверторный компрессор для систем кондиционирования на R32. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные.",
    "refrigerant": "R32",
    "specification": "Для кондиционеров",
    "price": 3615000,
    "stock": 8,
    "image": "/products/highly-asd-family.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-panasonic-9rs058hb",
    "sku": "DEMO-M033",
    "title": "Компрессор Panasonic 9RS058HB",
    "brand": "Panasonic",
    "model": "9RS058HB",
    "series": "R",
    "category": "Кондиционерные компрессоры",
    "description": "Роторный компрессор постоянной скорости для кондиционеров и климатических установок. Модель из официальной серии Panasonic R32. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. Panasonic серии R. На фото 5RS058FAA21 (R410A); модель 9RS058HB — другое исполнение на R32.",
    "refrigerant": "R32",
    "specification": "Для кондиционеров",
    "price": 3700000,
    "stock": 9,
    "image": "/products/real-compressor-9rs058hb.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "premium-c005",
    "sku": "DEMO-C005",
    "title": "Компрессор Panasonic 9RS096HA",
    "brand": "Panasonic",
    "model": "9RS096HA",
    "series": "R",
    "category": "Кондиционерные компрессоры",
    "description": "Роторный компрессор постоянной скорости для кондиционеров и климатических установок. Модель из официальной серии Panasonic R32. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. Panasonic серии R. На фото 5RS058FAA21 (R410A); модель 9RS096HA — другое исполнение на R32.",
    "refrigerant": "R32",
    "specification": "Для кондиционеров",
    "price": 2450000,
    "stock": 5,
    "image": "/products/real-compressor-9rs096ha.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-panasonic-9ps108ha",
    "sku": "DEMO-M035",
    "title": "Компрессор Panasonic 9PS108HA",
    "brand": "Panasonic",
    "model": "9PS108HA",
    "series": "P",
    "category": "Кондиционерные компрессоры",
    "description": "Роторный компрессор постоянной скорости для кондиционеров и климатических установок. Модель из официальной серии Panasonic R32. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. Panasonic серии P. На фото 5PS108EAA22 (R410A); модель 9PS108HA — другое исполнение на R32.",
    "refrigerant": "R32",
    "specification": "Для кондиционеров",
    "price": 3870000,
    "stock": 11,
    "image": "/products/real-compressor-9ps108ha.webp",
    "active": 1,
    "demo": 1
  },
  {
    "id": "model-panasonic-9ks170ha",
    "sku": "DEMO-M036",
    "title": "Компрессор Panasonic 9KS170HA",
    "brand": "Panasonic",
    "model": "9KS170HA",
    "series": "K",
    "category": "Кондиционерные компрессоры",
    "description": "Роторный компрессор постоянной скорости для кондиционеров и климатических установок. Модель из официальной серии Panasonic R32. Изображение иллюстрирует указанную серию; исполнение и комплектация подбираются по полному коду модели и паспорту оборудования. Цена и остаток демонстрационные. Panasonic серии K. На фото 5KS170EAB21 (R410A); модель 9KS170HA — другое исполнение на R32.",
    "refrigerant": "R32",
    "specification": "Для кондиционеров",
    "price": 3955000,
    "stock": 12,
    "image": "/products/real-compressor-9ks170ha.webp",
    "active": 1,
    "demo": 1
  }
];
