import { sqliteTable, text, integer, uniqueIndex, index, check } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
export const products = sqliteTable('products', {
 id: text('id').primaryKey(), sku: text('sku').notNull(), title: text('title').notNull(), brand: text('brand').notNull().default(''), model: text('model').notNull().default(''), series: text('series').notNull().default(''), category: text('category').notNull(), description: text('description').notNull(), refrigerant: text('refrigerant').notNull(), specification: text('specification').notNull(), price: integer('price').notNull(), stock: integer('stock').notNull(), image: text('image').notNull(), active: integer('active').notNull().default(1), demo: integer('demo').notNull().default(1)
}, t => [uniqueIndex('products_sku_unique').on(t.sku), check('nonnegative_stock',sql`${t.stock} >= 0`), check('nonnegative_price',sql`${t.price} >= 0`)]);
export const orders = sqliteTable('orders', {
 id: text('id').primaryKey(), userId: text('user_id').notNull(), requestKey: text('request_key').notNull(), requestHash: text('request_hash').notNull(), name: text('name').notNull(), phone: text('phone').notNull(), email: text('email').notNull(), delivery: text('delivery').notNull(), address: text('address').notNull(), comment: text('comment').notNull(), items: text('items').notNull(), total: integer('total').notNull(), status: text('status').notNull().default('new'), payment: text('payment').notNull().default('not_connected'), createdAt: text('created_at').notNull(), demo: integer('demo').notNull().default(1)
}, t=>[uniqueIndex('orders_user_request_unique').on(t.userId,t.requestKey),index('orders_user_created_idx').on(t.userId,t.createdAt)]);
export const notifications = sqliteTable('notifications', { id:text('id').primaryKey(), orderId:text('order_id').notNull().references(()=>orders.id), recipient:text('recipient').notNull(), channel:text('channel').notNull().default('unconfigured'), status:text('status').notNull().default('not_configured'), createdAt:text('created_at').notNull() });
export const settings = sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
